import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'apple-iphone-15-pro',
    name: 'iPhone 15 Pro',
    description: 'The ultimate iPhone. Forged in titanium and featuring the groundbreaking A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever.',
    price: 999.00,
    image: 'https://source.unsplash.com/400x400/?Apple%20iPhone%2015%20Pro',
    category: 'Phones',
  },
  {
    id: 'apple-macbook-air-m3',
    name: 'MacBook Air 13" (M3)',
    description: 'Supercharged by the M3 chip, the 13-inch MacBook Air is a supremely portable laptop that flies through work and play.',
    price: 1099.00,
    image: 'https://source.unsplash.com/400x400/?Apple%20Macbook%20Air',
    category: 'Computers',
  },
  {
    id: 'apple-ipad-pro-m4',
    name: 'iPad Pro 11" (M4)',
    description: 'The ultimate iPad experience with the breakthrough Ultra Retina XDR display, outrageous performance from the M4 chip, and support for Apple Pencil Pro.',
    price: 999.00,
    image: 'https://source.unsplash.com/400x400/?Apple%20iPad%20Pro',
    category: 'Tablets',
  },
  {
    id: 'apple-watch-s9',
    name: 'Apple Watch Series 9',
    description: 'A magical new way to use your Apple Watch without touching the screen. A display that’s twice as bright. And now you can choose a watch case and band combination that’s carbon neutral.',
    price: 399.00,
    image: 'https://source.unsplash.com/400x400/?Apple%20Watch%20Series%209',
    category: 'Watches',
  },
  {
    id: 'apple-airpods-pro-2',
    name: 'AirPods Pro (2nd Gen)',
    description: 'Re-engineered for even richer audio. Next-level Active Noise Cancellation and Adaptive Transparency. And Personalized Spatial Audio for immersive sound.',
    price: 249.00,
    image: 'https://source.unsplash.com/400x400/?Apple%20Airpods%20Pro',
    category: 'Accessories',
  },
  {
    id: 'apple-macbook-pro-m3',
    name: 'MacBook Pro 14" (M3)',
    description: 'The most advanced pro laptop ever. With the M3 Pro chip, it delivers game-changing performance and a stunning Liquid Retina XDR display.',
    price: 1599.00,
    image: 'https://source.unsplash.com/400x400/?Apple%20Macbook%20Pro',
    category: 'Computers',
  },
    {
    id: 'apple-vision-pro',
    name: 'Apple Vision Pro',
    description: 'An immersive new way to interact with your digital content. Vision Pro blends digital content with your physical space.',
    price: 3499.00,
    image: 'https://source.unsplash.com/400x400/?Apple%20Vision%20Pro',
    category: 'Entertainment',
  },
  {
    id: 'apple-homepod-mini',
    name: 'HomePod mini',
    description: 'Jam-packed with innovation, HomePod mini delivers unexpectedly big sound for a speaker of its size. It fits perfectly anywhere in the house.',
    price: 99.00,
    image: 'https://source.unsplash.com/400x400/?Apple%20Homepod%20Mini',
    category: 'Speakers',
  },
];